version: '3'
services:

  # MySQL Service
  db:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    environment:
        MYSQL_ROOT_PASSWORD: Siqueira_123
        MYSQL_DATABASE: app-node
        MYSQL_USER: DukaSiqueira
        MYSQL_PASSWORD: Siqueira_123
    volumes:
        - dbdata:/var/lib/mysql
    ports:
        - "3306:3306"
    networks:
        - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
    networks:
      - app-network

# Docker Networks
networks:
    app-network:
        driver: bridge

# Docker Volumes
volumes:
    dbdata:
        driver: local
